#!/usr/bin/env bash
# cards/ and sitemap.xml must agree, and the generator's markers must exist.
#
# These pages are GENERATED by savvy-backend/src/scripts/generate-card-pages.ts
# and committed here. Nothing re-runs that script automatically, so the
# committed set can drift from the catalog silently — which is exactly what
# happened: cards/citi_prestige.html stayed published, and stayed in the
# sitemap, long after the catalog discontinued that card and retired its rows.
# The generator DOES prune (stalePageFilenames), but only when a human runs it.
#
# This cannot detect catalog drift — that needs database access CI does not
# have. It detects the two failures that are visible from the repo alone:
#   1. a page with no sitemap entry, or a sitemap entry with no page
#   2. a missing/misordered marker pair, which makes --apply throw
set -euo pipefail
cd "$(dirname "$0")/../.."

fail=0
SITEMAP="sitemap.xml"

start="<!-- card-pages:start -->"
end="<!-- card-pages:end -->"
if ! grep -qF "$start" "$SITEMAP"; then
  echo "FAIL  $SITEMAP is missing $start — generate-card-pages.ts --apply will throw"; fail=1
fi
if ! grep -qF "$end" "$SITEMAP"; then
  echo "FAIL  $SITEMAP is missing $end — generate-card-pages.ts --apply will throw"; fail=1
fi
if [ "$fail" -eq 0 ]; then
  s_line=$(grep -nF "$start" "$SITEMAP" | head -1 | cut -d: -f1)
  e_line=$(grep -nF "$end" "$SITEMAP" | head -1 | cut -d: -f1)
  if [ "$s_line" -ge "$e_line" ]; then
    echo "FAIL  $start must come before $end (got lines $s_line and $e_line)"; fail=1
  else
    echo "OK    markers present and ordered ($s_line < $e_line)"
  fi
fi

# Pages on disk, excluding the generated index.
pages=$(find cards -maxdepth 1 -name '*.html' ! -name 'index.html' -exec basename {} \; | sort)
# Card entries in the sitemap, as filenames.
listed=$(grep -oE '<loc>[^<]*/cards/[^<]+\.html</loc>' "$SITEMAP" \
           | sed -E 's#.*/cards/([^<]+\.html)</loc>#\1#' | sort)

missing_from_sitemap=$(comm -23 <(printf '%s\n' "$pages") <(printf '%s\n' "$listed"))
missing_from_disk=$(comm -13 <(printf '%s\n' "$pages") <(printf '%s\n' "$listed"))

if [ -n "$missing_from_sitemap" ]; then
  echo "FAIL  page(s) on disk with no sitemap entry:"
  printf '        %s\n' $missing_from_sitemap
  fail=1
fi
if [ -n "$missing_from_disk" ]; then
  echo "FAIL  sitemap entr(ies) with no page on disk (would serve a 404):"
  printf '        %s\n' $missing_from_disk
  fail=1
fi
[ "$fail" -eq 0 ] && echo "OK    $(printf '%s\n' "$pages" | grep -c . ) card page(s) match the sitemap"

exit "$fail"
